import { t, useLanguage } from '../../../i18n/useLanguage';
import { useSearchParams } from 'react-router-dom';
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, List, Plus } from 'lucide-react';
import ManagerPageHeader from '../components/ManagerPageHeader';
import OverviewRowMenu from '../components/OverviewRowMenu';
import { BookingProgress } from '../components/OperationalOverview';
import { formatDate, formatTime, formatMoney } from '../../../utils/displayFormat';
import { localDateTime } from '../managerUtils';
import { addDays, eligibleClasses, weekRange, sessionDay, scheduleMetrics, subjectTone } from './operationsUtils';
import { readOperationsState, patchOperationsQuery, matchingClasses, pageItems, visibleSchedules, operationCounts } from './operationsState';
import { OperationEditor, SessionDrawer, OperationConfirmation, ClassDrawer, SessionGroupDrawer } from './OperationsDrawers';
import { OperationStatus } from './OperationsUI';
import './operations.css';
const listenNarrow=listener=>{const query=window.matchMedia('(max-width:1279px)');query.addEventListener('change',listener);return()=>query.removeEventListener('change',listener);};
const narrowSnapshot=()=>window.matchMedia('(max-width:1279px)').matches;
const emptyData={schedules:[],classes:[],subjects:[],rooms:[],coaches:[]};
const storedView=()=>{try{return localStorage.getItem('nexusOperationsView') || '';}catch{return '';}};
const sectionNames={schedules:'Schedules',classes:'Classes',catalog:'Catalog'};
export function OperationsSkeleton(){useLanguage();return <div className="ops-skeleton" role="status" aria-label={t('Loading Center Operations')}><div/><div/><div/></div>;}
function Empty({title='No matching results',children,action}){return <div className="ops-empty"><CalendarDays size={24}/><strong>{t(title)}</strong>{children && <p>{children}</p>}{action}</div>;}
function Filter({label,value,options,onChange,status=false,allowAll=true}){return <label>{t(label)}<select value={value} onChange={e=>onChange(e.target.value)}>{allowAll && <option value="">{t('All')}</option>}{options.map(([id,name])=><option key={id} value={id}>{status?t(name):name}</option>)}</select></label>;}
function SearchField({value,onChange,label}){
  const [local,setLocal]=useState({source:value,draft:value});const timer=useRef();
  if(local.source!==value) setLocal({source:value,draft:value});
  const draft=local.source===value?local.draft:value;
  useEffect(()=>{clearTimeout(timer.current);return()=>clearTimeout(timer.current);},[value]);
  useEffect(()=>()=>clearTimeout(timer.current),[]);
  return <label className="ops-query-field">{t(label)}<input type="search" value={draft} placeholder={t(label)} onChange={e=>{const text=e.target.value;setLocal({source:value,draft:text});clearTimeout(timer.current);timer.current=setTimeout(()=>onChange(text),300);}}/></label>;
}
function Pager({block,onPage,onSize,size}){return <nav className="ops-pagination" aria-label={t('Pagination')}><span>{t('{0}–{1} of {2}',[block.start,block.end,block.total])}</span>{onSize && <label>{t('Rows per page')}<select value={size} onChange={e=>onSize(Number(e.target.value))}>{[20,50,100].map(n=><option key={n}>{n}</option>)}</select></label>}<button className="manager-icon-button" aria-label={t('Previous page')} disabled={block.page===1} onClick={()=>onPage(block.page-1)}><ChevronLeft size={16}/></button><span>{t('Page {0} of {1}',[block.page,block.pages])}</span><button className="manager-icon-button" aria-label={t('Next page')} disabled={block.page===block.pages} onClick={()=>onPage(block.page+1)}><ChevronRight size={16}/></button></nav>;}
function Tabs({items,value,onChange,label,prefix}){return <div role="tablist" className="manager-tabs" aria-label={t(label)}>{items.map(([id,name,count,hint],i)=><button key={id} id={`${prefix}-${id}`} role="tab" aria-selected={value===id} aria-controls={`${prefix}-panel-${id}`} tabIndex={value===id?0:-1} className={value===id?'active':''} title={hint?t(hint):undefined} onClick={()=>onChange(id)} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowRight'?1:items.length-1))%items.length;onChange(items[next][0]);document.getElementById(`${prefix}-${items[next][0]}`)?.focus();}}>{t(name)}{count!==undefined && <span>{count}</span>}</button>)}</div>;}

export default function OperationsPage({data,page,filters,appliedFilters,setFilters,reload,refresh,loading,loadError,notify}){
  const language=useLanguage();const [query,setQuery]=useSearchParams();const narrow=useSyncExternalStore(listenNarrow,narrowSnapshot);
  const state=readOperationsState(query,narrow,storedView());const records=data || emptyData;
  const patch=(values,replace=false)=>setQuery(current=>patchOperationsQuery(current,values),{replace});
  useEffect(()=>{document.title=`${t(sectionNames[state.tab])} – NEXUS`;},[state.tab,language]);
  const [editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[classDetail,setClassDetail]=useState(null),[cell,setCell]=useState(null),[confirmation,setConfirmation]=useState(null);
  const range={from:query.get('from') || appliedFilters.from,to:query.get('to') || appliedFilters.to};
  const week=weekRange(range.from);const wholeWeek=range.from===week.from && range.to===week.to;
  const rows=visibleSchedules(records.schedules,records.classes,state,range,query);const metrics=scheduleMetrics(rows);
  // Interim client filtering/sorting/pagination: API returns all classes/catalog records, not a server page.
  const classes=matchingClasses(records.classes,state.classes,language);const classPage=pageItems(classes,state.classes.page,state.classes.size);
  const schedulePage=pageItems(rows,state.schedulePage,20);const counts=operationCounts(rows,classes);
  const coaches=[...new Map([...records.classes.map(row=>[row.coachId,{userId:row.coachId,fullName:row.coachName}]),...records.coaches.map(row=>[row.userId,row])]).values()];
  const options={subject:records.subjects.map(r=>[r.subjectId,r.subjectName]),coach:coaches.map(r=>[r.userId,r.fullName]),room:records.rooms.map(r=>[r.roomId,r.roomName])};
  const changeRange=value=>{const next={...filters,...value};setFilters(next);reload(next);patch({...value,sPage:1});};
  const chooseView=value=>{try{localStorage.setItem('nexusOperationsView',value);}catch{/* Optional storage. */}if(value==='calendar' && !wholeWeek){const next={...filters,...week};setFilters(next);reload(next);patch({...week,scheduleView:value,sPage:1});}else patch({scheduleView:value});};
  const createSession=(day,resource={})=>{const start=new Date();start.setMinutes(0,0,0);start.setHours(start.getHours()+1);const end=new Date(start);end.setHours(end.getHours()+1);const candidates=eligibleClasses(records.classes,resource,state.selection);setEditor({type:'schedule',resource,candidates,initial:{classId:candidates.length===1?candidates[0].classId:'',startTime:day?`${day}T09:00`:localDateTime(start.toISOString()),endTime:day?`${day}T10:00`:localDateTime(end.toISOString())}});};
  const linked=records.schedules.find(r=>String(r.scheduleId)===query.get('editSchedule'));const activeEditor=editor || (linked?{type:'schedule',item:linked}:null);
  const closeEditor=()=>{setEditor(null);if(query.has('editSchedule'))patch({editSchedule:null},true);};
  const saved=async message=>{closeEditor();setConfirmation(null);setDetail(null);setClassDetail(null);notify?.(t(message));await refresh();};
  const classChange=values=>patch({...values,cPage:1});
  const clearClasses=()=>classChange({cQuery:null,cSubject:null,cCoach:null,cRoom:null,cStatus:'ACTIVE'});
  const recurring=row=>setEditor({type:'series',initial:{classId:row.classId}});
  const futureInRange=row=>records.schedules.filter(s=>s.classId===row.classId && s.status==='SCHEDULED' && new Date(`${localDateTime(s.startTime)}+07:00`)>new Date()).length;
  const classActions=row=>[{label:'Edit',run:()=>setEditor({type:'class',item:row})},{label:'Create recurring sessions',disabled:row.status!=='ACTIVE',run:()=>recurring(row)},{label:'Deactivate',danger:true,disabled:row.status!=='ACTIVE',run:()=>setConfirmation({type:'deactivate',item:row,upcomingInRange:futureInRange(row)})}];
  const actions=state.tab==='catalog'?null:<button className="manager-primary" disabled={loading || !!loadError} onClick={()=>state.tab==='classes'?setEditor({type:'class'}):createSession()}><Plus size={16}/>{t(state.tab==='classes'?'Create class':'Create session')}</button>;
  return <div className="ops-page" aria-busy={loading}>
    <ManagerPageHeader title={t(page.title)} description={t('Plan the week, manage classes and keep resources coordinated.')} actions={actions}/>
    <Tabs prefix="ops-tab" label="Operations sections" value={state.tab} onChange={tab=>patch({tab})} items={[["schedules","Schedules",counts.schedules,'Sessions matching current filters in the visible date range.'],['classes','Classes',counts.classes,'Classes matching current filters.'],['catalog','Catalog']]}/>
    <section id={`ops-tab-panel-${state.tab}`} role="tabpanel" aria-labelledby={`ops-tab-${state.tab}`}>
      {loadError?<Empty title="Operations data could not be loaded." action={<button className="manager-secondary" onClick={refresh}>{t('Retry')}</button>}/>:loading?<OperationsSkeleton/>:state.tab==='schedules'?<>
        {(query.has('lowRegistration') || query.has('excludeCancelled')) && <div className="manager-alert"><span>{t(query.has('lowRegistration')?'Low bookings · upcoming scheduled sessions below 25% capacity':'Today’s sessions · cancellations excluded')}</span><button onClick={()=>patch({lowRegistration:null,excludeCancelled:null,excludeUrgent:null,status:null,sPage:1})}>{t('Clear filter')}</button></div>}
        <div className="ops-stat-grid">{[['Sessions today',metrics.today],['Sessions in range',metrics.sessions],['Seat occupancy',`${Math.round(metrics.occupancy*100)}%`],['Low registrations',metrics.low]].map(([label,value])=><article className="ops-stat" key={label}><small>{t(label)}</small><strong>{value}</strong></article>)}</div>
        <div className="ops-toolbar"><div className="ops-week-nav"><button className="manager-icon-button" aria-label={t('Previous week')} onClick={()=>changeRange(weekRange(addDays(week.from,-7)))}><ChevronLeft size={18}/></button><button className="manager-secondary" onClick={()=>changeRange(weekRange())}>{t('Today')}</button><button className="manager-icon-button" aria-label={t('Next week')} onClick={()=>changeRange(weekRange(addDays(week.from,7)))}><ChevronRight size={18}/></button><strong>{formatDate(range.from)} – {formatDate(range.to)}</strong></div><div className="ops-view-controls"><Filter label="Group by" allowAll={false} value={state.group} options={[["room",t('Room')],["coach",t('Coach')]]} onChange={group=>patch({group})}/><div className="ops-segment"><button aria-pressed={state.view==='calendar' && wholeWeek} onClick={()=>chooseView('calendar')}><CalendarDays size={16}/>{t('Week')}</button><button aria-pressed={state.view==='list' || !wholeWeek} onClick={()=>chooseView('list')}><List size={16}/>{t('List')}</button></div></div></div>
        <div className="ops-filter-grid ops-resource-filters">{['subject','coach','room'].map(key=><Filter key={key} label={{subject:'Subject',coach:'Coach',room:'Room'}[key]} value={state.selection[key]} options={options[key]} onChange={value=>patch({[{subject:'sSubject',coach:'sCoach',room:'sRoom'}[key]]:value,sPage:1,resourcePage:1})}/>)}<Filter label="Status" status value={state.selection.status} options={['SCHEDULED','COMPLETED','CANCELLED'].map(code=>[code,code[0]+code.slice(1).toLowerCase()])} onChange={status=>patch({status,sPage:1})}/><button className="manager-secondary" onClick={()=>patch({sSubject:null,sCoach:null,sRoom:null,status:null,sPage:1,resourcePage:1})}>{t('Clear filters')}</button></div>
        {state.view==='list' || !wholeWeek ? <><ScheduleList rows={schedulePage.items} open={setDetail}/><Pager block={schedulePage} onPage={sPage=>patch({sPage})}/></>:<WeekCalendar rows={rows} data={records} week={week} state={state} query={query} patch={patch} open={setDetail} create={createSession} more={setCell}/>}
        <p className="ops-note">{t('Calendar chips show sessions in chronological order, not a time axis; use details to compare times and check overlaps.')}</p>
      </>:state.tab==='classes'?<>
        <div className="ops-class-toolbar"><SearchField value={state.classes.search} label="Search classes" onChange={value=>classChange({cQuery:value})}/>{['subject','coach','room'].map(key=><Filter key={key} label={{subject:'Subject',coach:'Coach',room:'Room'}[key]} value={state.classes[key]} options={options[key]} onChange={value=>classChange({[{subject:'cSubject',coach:'cCoach',room:'cRoom'}[key]]:value})}/>)}<Filter label="Status" value={state.classes.status==='ALL'?'':state.classes.status} status options={[["ACTIVE","Active"],["INACTIVE","Inactive"]]} onChange={value=>classChange({cStatus:value || 'ALL'})}/><button className="manager-secondary" onClick={clearClasses}>{t('Clear filters')}</button></div>
        <div className="manager-table-wrap ops-compact-table"><table><thead><tr>{[['Class / subject','className'],['Coach / room','coachName'],['Capacity / session','maxSlots'],['Tuition / class registration','price']].map(([label,key])=><th key={key} aria-sort={state.classes.sort===key?(state.classes.dir==='asc'?'ascending':'descending'):'none'}><button className="ops-sort" onClick={()=>classChange({cSort:key,cDir:state.classes.sort===key && state.classes.dir==='asc'?'desc':'asc'})}>{t(label)} {state.classes.sort===key?(state.classes.dir==='asc'?'↑':'↓'):'↕'}</button></th>)}<th>{t('Status')}</th><th>{t('Actions')}</th></tr></thead><tbody>{classPage.items.map(row=><tr key={row.classId} className={row.status==='INACTIVE'?'ops-inactive':''}><td><button className="overview-class-button" onClick={()=>setClassDetail(row)}>{row.className}</button><small className="manager-cell-sub">{row.subjectName}</small></td><td>{row.coachName}<small className="manager-cell-sub">{row.roomName}</small></td><td>{row.maxSlots}<small className="manager-cell-sub" title={t('Highest confirmed + pending booking count of any non-cancelled session.')}>{t('Highest bookings in one session: {0}',[row.enrolled || 0])}</small></td><td>{formatMoney(row.price)}</td><td>{row.status==='INACTIVE' && <OperationStatus status={row.status}/>}</td><td><OverviewRowMenu row={row} items={classActions(row)}/></td></tr>)}</tbody></table>{!classes.length && <Empty title={!records.classes.length?'No classes yet':'No classes match your filters'} action={<button className="manager-secondary" onClick={!records.classes.length?()=>setEditor({type:'class'}):clearClasses}>{t(!records.classes.length?'Create class':'Clear filters')}</button>}/>}</div>
        <Pager block={classPage} size={state.classes.size} onSize={cSize=>classChange({cSize})} onPage={cPage=>patch({cPage})}/><p className="ops-note">{t('Classes with future sessions cannot be deactivated; cancel those sessions first.')}</p>
      </>:<>
        <Tabs prefix="ops-catalog" label="Catalog sections" value={state.catalog} onChange={catalog=>patch({catalog,catalogQuery:null,catalogPage:1})} items={[["subjects","Subjects",records.subjects.length],["rooms","Rooms",records.rooms.length]]}/>
        <div id={`ops-catalog-panel-${state.catalog}`} role="tabpanel" aria-labelledby={`ops-catalog-${state.catalog}`}><Catalog type={state.catalog==='subjects'?'subject':'room'} records={records} search={state.catalogSearch} page={state.catalogPage} patch={patch} create={type=>setEditor({type})} edit={(type,item)=>setEditor({type,item})}/></div>
      </>}
    </section>
    {activeEditor && <OperationEditor config={activeEditor} data={records} onClose={closeEditor} onSaved={saved}/>}
    {detail && !activeEditor && !confirmation && <SessionDrawer schedule={records.schedules.find(r=>r.scheduleId===detail.scheduleId) || detail} onClose={()=>setDetail(null)} edit={item=>setEditor({type:'schedule',item})} confirm={(type,item)=>setConfirmation({type,item})}/>}
    {classDetail && !activeEditor && !confirmation && <ClassDrawer row={classDetail} upcomingInRange={futureInRange(classDetail)} onClose={()=>setClassDetail(null)} edit={()=>setEditor({type:'class',item:classDetail})} recurring={()=>recurring(classDetail)}/>}
    {cell && !detail && <SessionGroupDrawer cell={cell} onClose={()=>setCell(null)} open={setDetail}/>}
    {confirmation && <OperationConfirmation config={confirmation} onClose={()=>setConfirmation(null)} onSaved={saved}/>}
  </div>;
}
function ScheduleList({rows,open}){if(!rows.length)return <Empty title="No matching sessions"/>;const grouped=new Map();for(const row of rows){const day=sessionDay(row.startTime);if(!grouped.has(day))grouped.set(day,[]);grouped.get(day).push(row);}return <div className="ops-session-list">{[...grouped].map(([day,items])=><section className="ops-list-group" key={day}><h2>{formatDate(day)} <small>{t('{0} sessions',[items.length])}</small></h2>{items.map(row=><div className="ops-list-compact" key={row.scheduleId}><time>{formatTime(row.startTime)}–{formatTime(row.endTime)}</time><div><button className="overview-class-button" onClick={()=>open(row)}>{row.className}</button><small>{row.coachName} · {row.roomName}</small><OperationStatus status={row.status} row={row} hideScheduled/></div><BookingProgress row={row} now={new Date()}/><button className="manager-icon-button" aria-label={t('View session {0}',[row.className])} onClick={()=>open(row)}><ChevronRight size={16}/></button></div>)}</section>)}</div>;}
function WeekCalendar({rows,data,week,state,query,patch,open,create,more}){
  const days=Array.from({length:7},(_,i)=>addDays(week.from,i));const resourceKey=state.group==='room'?'roomId':'coachId';
  const allResources=state.group==='room'?data.rooms.map(r=>({id:r.roomId,name:r.roomName})):[...new Map(data.classes.map(r=>[r.coachId,{id:r.coachId,name:r.coachName}])).values()];
  const resourcePage=pageItems(allResources.filter(r=>!state.selection[state.group] || String(r.id)===state.selection[state.group]),Number(query.get('resourcePage')) || 1,10);
  const cells=new Map();const totals=new Map();for(const row of rows){const key=`${row[resourceKey]}-${sessionDay(row.startTime)}`;if(!cells.has(key))cells.set(key,[]);cells.get(key).push(row);totals.set(row[resourceKey],(totals.get(row[resourceKey]) || 0)+1);}
  return <>{!resourcePage.total?<Empty title="No matching resources"/>:<><div className="ops-calendar-scroll" role="region" aria-label={t('Weekly schedule by resource')} tabIndex={0}><div className="ops-calendar"><div className="ops-calendar-heading"><strong>{t(state.group==='room'?'Rooms':'Coaches')}</strong>{days.map(day=><div key={day}><span>{t(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][new Date(`${day}T12:00`).getDay()])}</span><strong>{formatDate(day)}</strong></div>)}</div>{resourcePage.items.map(resource=><div className="ops-resource-row" key={resource.id}><div className="ops-resource-label"><strong>{resource.name}</strong><small>{t('{0} sessions',[totals.get(resource.id) || 0])}</small></div>{days.map(day=>{const sessions=cells.get(`${resource.id}-${day}`) || [];const resourceFilter={[resourceKey]:resource.id};const canCreate=eligibleClasses(data.classes,resourceFilter,state.selection).length>0;return <div className="ops-day-cell" key={day}>{sessions.slice(0,3).map(row=><button className={`ops-calendar-session ops-tone-${subjectTone(data.classes.find(c=>c.classId===row.classId)?.subjectId)}`} key={row.scheduleId} title={t('{0} · {1}–{2} · {3} · {4} · {5}/{6}',[row.className,formatTime(row.startTime),formatTime(row.endTime),row.coachName,row.roomName,row.booked || 0,row.maxSlots])} aria-label={t('View session {0}',[row.className])} onClick={()=>open(row)}><time>{formatTime(row.startTime)}–{formatTime(row.endTime)}</time><strong>{row.className}</strong><BookingProgress row={row} now={new Date()}/><OperationStatus status={row.status} row={row} hideScheduled/></button>)}{sessions.length>3 && <button className="ops-more" onClick={()=>more({title:resource.name,day,rows:sessions})}>{t('+{0} more sessions',[sessions.length-3])}</button>}{canCreate && <button className="ops-cell-create" aria-label={t('Create session on {0} at 09:00 for {1}',[formatDate(day),resource.name])} onClick={()=>create(day,resourceFilter)}><Plus size={14}/>{t('Add session')}</button>}</div>;})}</div>)}</div></div>{resourcePage.total>10 && <Pager block={resourcePage} onPage={resourcePage=>patch({resourcePage})}/>}</> }</>;
}
function Catalog({type,records,search,page,patch,create,edit}){
  const all=records[`${type}s`];const rows=all.filter(row=>`${row[`${type}Name`]} ${row.description || ''}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));const block=pageItems(rows,page,20);
  return <><div className="ops-toolbar"><SearchField value={search} label={type==='subject'?'Search subjects':'Search rooms'} onChange={catalogQuery=>patch({catalogQuery,catalogPage:1})}/><button className="manager-primary" onClick={()=>create(type)}><Plus size={16}/>{t(type==='subject'?'Add subject':'Add room')}</button></div><div className="manager-table-wrap ops-compact-table ops-catalog-table"><table><thead><tr><th>{t('Name')}</th><th>{t(type==='subject'?'Description':'Capacity')}</th><th>{t('Classes')}</th><th>{t('Actions')}</th></tr></thead><tbody>{block.items.map(row=><tr key={row[`${type}Id`]}><td>{row[`${type}Name`]}</td><td>{type==='subject'?<span className="ops-description" title={row.description || t('No description')}>{row.description || t('No description')}</span>:row.capacity}</td><td><span className={!row.classCount?'ops-zero':''} title={!row.classCount?t('No classes yet'):undefined}>{row.classCount || 0}</span></td><td><button className="manager-secondary" aria-label={t('Edit {0}',[row[`${type}Name`]])} onClick={()=>edit(type,row)}>{t('Edit')}</button></td></tr>)}</tbody></table>{!rows.length && <Empty title="No matching results" action={search?<button className="manager-secondary" onClick={()=>patch({catalogQuery:null,catalogPage:1})}>{t('Clear filters')}</button>:null}/>}</div>{all.length>20 && <Pager block={block} onPage={catalogPage=>patch({catalogPage})}/>}</>;
}
